### ISSUE TITLE
Build error in 'open(completion:)' API when Deployment target is set to 16.2

### ISSUE THREAD

**Issue by Moonubanna** [star-micronics/StarXpand-SDK-iOS#12]
Please check screenshot:
I am trying to run project on Xcode version: Version 14.2 (14C18), Deployment target: 16.2
'open(completion:)' is unavailable in iOS: Not available on iOS 13 or later: Please use open() async. This deprecated warning also appears when the iOS deployment target is set to iOS 12, but this method works properly on iOS 12

<img width="856" alt="Screenshot 2023-02-13 at 11 28 41 AM" src="https://user-images.githubusercontent.com/17289834/218397376-28df3c81-8c38-4fe9-bf30-91cb030978cb.png">

**Comment by bandit-ibayashi** [comment]
@Moonubanna If you set "iOS Deployment Target" to iOS 13.0 or later, please remove the API to use the [StarPrinter](https://star-m.jp/products/s_print/sdk/starxpand/manual/en/ios-swift/api-reference/star-printer/index.html) class method that uses completion and the code associated with it.

The sample code in this repository is compatible with iOS12 or later, while Swift Concurrency is only available for iOS13 or later. For this reason, we have prepared separate sample code for iOS12 and iOS13 or later.
