### ISSUE TITLE
Printing failing when default gateway / router IP is different.

### ISSUE THREAD

**Issue by asa47** [star-micronics/StarXpand-SDK-iOS#14]
## Description
Not sure if it falls under a bug or feature request, if it is not correct please feel free to change it.

We replaced StarPRNT-SDK-iOS-Swift with the new StarXpand-SDK-iOS. The new SDK works great but we have noticed the following issue:

StarXpand-SDK-iOS can only print to printers that are connected to the same network. As soon as the printers are connected to a different network (different router IP / default gateway), it stops printing to those devices even though the printer can still be ping through the printer's IP address. 

In theory if the iOS device can use Safari to ping the printer through the printer's IP address, it should also be able to print to the printer location but something is blocking this.

## Your device where the bug occurs 
 - Device: iPad mini (5th generation)
 - OS: iOS 15.5
 - Browser: Safari
 - Version: Latest

## Your printer
- Model Names: mC-Print2
- Firmware Version: 1.0.0
- Interface: Ethernet

## Your development environment
The result of executing the command `ver` on Windows, `sw_vers` on macOS, `uname –a` on Linux, or these equivalent commands.

ProductName:		macOS
ProductVersion:		13.3.1
ProductVersionExtra:	(a)
BuildVersion:		22E772610a

## To Reproduce

I understand that the following might be a complicated setup, and that it might not affect many people.

1. We have two different broadband connections (Network A and Network B)
2. An Omada router is used to bonds the two external broadband connections together and then provides a LAN with VLAN’s.
3. Network A is only used for VLAN connections, and the devices are connected through WIFI.
4. Network B is only used for LAN connections, and the printers are connected through ethernet ports.
5. If everything is done correctly, the devices connected to the VLAN should be able to ping the printers connected to the LAN.
6. When sending a request to print to the printer IP address, the request fails with the following error: "Device not found."

## Expected behavior
In the previous SDK (StarPRNT-SDK-iOS-Swift), as long as we were able to ping the printer from the iPad through the printer's IP address, we were able to print to it. Do you thinks it would be possible to add this again?

## Additional context
We tested this in both StarPRNT-SDK-iOS-Swift and StarXpand-SDK-iOS:

- StarPRNT-SDK-iOS-Swift can print to printers even though they are on a different network.
- StarXpand-SDK-iOS can only print to printers that are on the same network.

**Comment by bandit-ibayashi** [comment]
@asa47 Thank you for the migration to StarXpand SDK and this report.

Please let us confirm two points on this issue for information to confirm it.
1. Would the printer be able to be found when using our disvovery API in StarXpand SDK?
   We hope you can see this in the [Discovery](https://github.com/star-micronics/StarXpand-SDK-iOS/blob/main/example/StarXpandSDK/DiscoveryViewController.swift) function of [the SDK sample](https://github.com/star-micronics/StarXpand-SDK-iOS/tree/main/example/StarXpandSDK).

2. Could you please let us know how to specify the printer to print to?
   From your above report, I assume that you have probably specified the IP address of that printer as the [identifier](https://star-m.jp/products/s_print/sdk/starxpand/manual/en/ios-swift-api-reference/star-connection-settings/identifier.html#ios-swift-star-connection-settings-identifier) in [StarConnectionSettings](https://star-m.jp/products/s_print/sdk/starxpand/manual/en/ios-swift-api-reference/star-connection-settings/index.html#ios-swift-star-connection-settings). But please allow me to clarify this, just to be sure.

**Comment by asa47** [comment]
@bandit-ibayashi Thanks for the reply, please see the following:

1. No, the printers are not discoverable through the discovery API, and this is expected since the printers are on a different network, routers always rejects broadcast traffic from external devices. 
We also tested this on both StarPRNT-SDK-iOS-Swift and StarXpand-SDK-iOS, on both SDKs the printers were not discoverable.

2. We assigned a static IP address to all the printers (i.e. TCP:192.168.2.1/24), so the app knows beforehand where to send the print request. We also know the IP address is correct because we can access the printer utility page through the printer IP address. 

We are not sure why it's working on the old SDK but I am assuming there might be something blocking the request from being sent. Please let me know if you need additional information from our side, I would be happy to help!

**Comment by bandit-ibayashi** [comment]
@asa47 Thank you for your prompt reply and letting us know this information. It gave a better understanding of the situation.
Please wait a moment while we investigate. Thank you!

**Comment by Tatsuki-Yamamoto2731** [comment]
@asa47 This problem was fixed at V2.5.0 ([change log](https://github.com/star-micronics/StarXpand-SDK-iOS/blob/main/CHANGELOG.md#change-log)). Thank you for your report.
