### ISSUE TITLE
Opening the cash Drawer?

### ISSUE THREAD

**Issue by DaveTTS** [star-micronics/StarXpand-SDK-iOS#15]
Hi there

Is there any chance of a quick demo on how to open the cash drawer of an MPOS.  

I get the delegates and everything, I just cannot figure how to get the API to open up the cash drawer and can find no example.

Thanks
David

**Comment by YuzoKato** [comment]
We have a document to use the cash drawer. Please read the document from the link below and let us know if you have a question.
https://star-m.jp/products/s_print/sdk/starxpand/manual/en/cashDrawer.html
