### ISSUE TITLE
tsp100III Series print issue 

### ISSUE THREAD

**Issue by reymondcv9** [star-micronics/StarXpand-SDK-iOS#17]
## Description
Im using the latest code as an spm. I was successfully able to print using the documentation provided and it works perfect on printer tsp650II, But I have tested printing the same receipt on a printer tsp100III and it's not working. When I say it's not working Im referring that it's not printing the same data that I see while printing on tsp650II. 

## Your device where the bug occurs 
 - Device: 
    iPad 10, iPhone 14 Pro
 - OS:
    iPad OS 15 (latest public) , iOS16.5.1
 - Browser: 
    Printing from app 
 - Version
    latest sdk

## Your printer
- Model Names:
   tsp100III
- Firmware Version:
    latest
- Interface:
    Wifi & Lan same issue

## To Reproduce
Im able to discover printers locally no problem, I select printer from list, I store printer identifier and interface locally to use in future when printing.

On tsp100III when I try to print its only printing part of the recipe. I even used a sample code you offer in this sample Xcode project and that is also not printing properly. 

## Expected behavior
When printing using printer tsp100III I expect to get same result as tsp650II

## Screenshots
When printing receipt using tsp100III printer
![480ccd1f-0606-4790-aec3-3b21ddd47cf5](https://github.com/star-micronics/StarXpand-SDK-iOS/assets/51859408/a27a7c39-e9e0-4e59-86c5-c1a8964ad3ad)

When printing same receipt using  tsp650II printer:
![IMG_1094](https://github.com/star-micronics/StarXpand-SDK-iOS/assets/51859408/f9607364-9a5b-469d-b134-d48f59b71a47)

## Additional context
I have old code using previous sdk that I implemented in my app years ago, the printer tsp100III works fine on that older sdk

**Comment by gare-bear** [comment]
@reymondcv9 the text is missing from your receipt because the TSP100III series are graphics-only. They can only print if the receipt is rendered as an image. That's why you get the logo and the QR code, but not the body of the receipt.

TSP650II series are capable of text & graphics and you don't run into this issue.
