### ISSUE TITLE
Sending printing commands while monitoring a Printer

### ISSUE THREAD

**Issue by cumanzor** [star-micronics/StarXpand-SDK-iOS#18]

**Comment by gare-bear** [comment]
Hi @cumanzor,
I edited your comment to the original one you posted last week.
If you solved your issue, you can simply mark it as completed.
No need to delete the original description as it might help others with similar questions.

Even better if you could share your solution (maybe this was covered in our documentation).

**Comment by cumanzor** [comment]
Hey @gare-bear. Yeah I closed this as this was a non issue. You can monitor a printer and still send commands *as long as the port is still opened*. That is, as long as you don't call `close()` in the `StarPrinter` device. The monitoring code sample was closing the port, and I assumed this was required. Just an oversight.

**Comment by gare-bear** [comment]
got it! thanks for sharing your feedback!
