### ISSUE TITLE
Support asynchronous calls on iOS 13 and above

### ISSUE THREAD

**Issue by robertsammons** [star-micronics/StarXpand-SDK-iOS#2]
Now that async calls are available on older iOS versions it doesn't make sense to gate keep these behind iOS 15 availability.

Is it possible to support async on these older ones, or at least to remove the deprecation warning which seems unnecessary.

**Comment by bandit-ibayashi** [comment]
@robertsammons Now it is possible to use methods using async in StarPrinter class in iOS 13 and later by v2.0.0 update.
It would be very helpful if you could use [this page](https://star-m.jp/products/s_print/sdk/starxpand/manual/en/ios-swift/migration/index.html) as a reference for the migration.

We much appreciate your report!

**Comment by robertsammons** [comment]
Thanks for the update and sorting this out 👍🏻
