### ISSUE TITLE
[REQUEST] .NET MAUI iOS Support Request

### ISSUE THREAD

**Issue by Nguyenthanhtoa** [star-micronics/StarXpand-SDK-iOS#21]
## Is your feature request related to a problem? Please describe.
I'm developing an iOS application which integrating with Start printer on .NET MAUI. 
I tried to use this library https://github.com/star-micronics/starlabs-starprnt-sdk-xamarin but it doesn't work . It got an error when building library.

## Describe the solution you'd like
N/A

## Describe alternatives you've considered
N/A

## Additional context
Can you please give me an advice? Does StarIO is support for .NET MAUI?

**Comment by mezaniella** [comment]
I have an app in Xamarin that I migrated to MAUI. The .dlls in that repository do not work. I don't know whether to make StarXpand or StarPRNT bindings.

**Comment by Nguyenthanhtoa** [comment]
Hi @mezaniella, I got the same issue but the issue only occurr on iOS only, I found a work around on Android that we can use [the original sdk](https://github.com/star-micronics/StarPRNT-SDK-Android-Java) to build android library (.jar) and then create an Android binding project for implementation.

**Comment by Tatsuki-Yamamoto2731** [comment]
@Nguyenthanhtoa @mezaniella
Unfortunately, we have no plan to support .NET MAUI so far. Sorry for any inconvenience.
I am closing this Issue, but we received your feedback.

**Comment by linnkrb** [comment]
So do you have a recommendation on what to do for all of us that is upgrading from Xamarin to maui ?
