### ISSUE TITLE
TSP658II fails to detect with StarXpand 2.5.0

### ISSUE THREAD

**Issue by mortenbekditlevsen** [star-micronics/StarXpand-SDK-iOS#22]
## Description
A customer reported that the Star TSP650II fails to detect with the StarXpand SDK.
We got a hold of this printer, and indeed we see that it fails to be detected (the model case .unknown) is returned when the printer is discovered.

## Your device where the bug occurs 
 - Device: 
    iPhone 13, iPad 4th gen
 - OS:
    iOS 17
 - Browser: 
    No browser
 - Version
    ?

## Your printer
- Model Names:
    TSP650II
- Firmware Version:
    When printing self test from Star Setup Utility, the printer prints both 7 and 4.6 - uncertain which one is the requested firmware version.
- Interface:
    Bluetooth

## Your development environment
ProductName:		macOS
ProductVersion:		14.1.1
BuildVersion:		23B81

## Expected behavior
I expect the Star TSP650II to detect with the model .tsp650II that is present in the StarXpand SDK.

I can detect this same printer with the StarPrnt SDK

## Additional context
Add any other context about the bug here.

**Comment by YuzoKato** [comment]
In StarXpand SDK, you can use [identifier](https://star-m.jp/products/s_print/sdk/starxpand/manual/en/ios-swift-api-reference/star-connection-settings/identifier.html#ios-swift-star-connection-settings-identifier) to show "Star Micronics". Once the library communicates with TSP654II, it can get "TSP650II" as [model name](https://star-m.jp/products/s_print/sdk/starxpand/manual/en/ios-swift-api-reference/star-printer-information/model.html#ios-swift-star-printer-information-model). You cannot get the model name before the communication.

**Comment by mortenbekditlevsen** [comment]
Hi @YuzoKato ,
Thank you for your reply. 
I am familiar with the fact that you need to connect to the printer before you can get its model. 
We are building a POS system and we are integrating to many different Star printers. 
The model in question is the only one that still returns '.unknown' for the model property even after it has been connected to.

**Comment by YuzoKato** [comment]
Thank you for integrating many Star printers!!

"Connect" here means "[open](https://star-m.jp/products/s_print/sdk/starxpand/manual/en/ios-swift-api-reference/star-printer/open-async.html#ios-swift-star-printer-open-async) " by our library. Then, the library can get the model name "TSP654II". Just after pairing, the library can discover only "Star Micronics".  If you refer to [identifier](https://star-m.jp/products/s_print/sdk/starxpand/manual/en/ios-swift-api-reference/star-connection-settings/identifier.html#ios-swift-star-connection-settings-identifier) at discovery, you can get "Star Micronics".

StarPRNT can get "Star Micronics" as a model name for TSP654II Bluetooth at search as well, not "TSP654II". 

Please let me know if you have any questions.

**Comment by Tatsuki-Yamamoto2731** [comment]
I am closing this Issue. If you still have this issue, please reopen it.
