### ISSUE TITLE
TSP100IIILAN / TSP143LAN not printing text, only images

### ISSUE THREAD

**Issue by davidhole** [star-micronics/StarXpand-SDK-iOS#24]
## Description
Whenever actionPrintText is used in a PrinterBuilder, it seems to be ignored in the final printout.

This can be seen using your included example app, with the final printout looking like this:
![IMG_9100](https://github.com/star-micronics/StarXpand-SDK-iOS/assets/1480046/ca75511d-a19f-4fbf-bfdf-1cc663615d5e)

## Your device where the bug occurs 
 - Device: 
     iPhone 15 Pro Max
 - OS:
    iOS 17.1.1

## Your printer
- Model Names:
    TSP100IIILAN / TSP143LAN
- Interface:
    Ethernet

## Your development environment
ProductName:		macOS
ProductVersion:		14.1.1
BuildVersion:		23B81

## To Reproduce
1. Open the included example app from this repo
2. Click Discover to find printer MAC
3. Go back and select Print.
4. Enter MAC in address (adding in colons)
5. Press Print
6. Only images print as part of test print, no text is printed.

## Expected behavior
A full printout including all text, as it appears on mPOP and other printers

## Screenshots
![IMG_9100](https://github.com/star-micronics/StarXpand-SDK-iOS/assets/1480046/ca75511d-a19f-4fbf-bfdf-1cc663615d5e)

**Comment by mortenbekditlevsen** [comment]
I don't work for Star, but aren't those printer precisely graphics-only printers?

**Comment by davidhole** [comment]
Hi @mortenbekditlevsen.

No the SDK has all sorts of methods for text, graphics, QR codes, barcodes, etc.
All of these methods work well on other printers in the lineup (mPOP) but not on this printer.

It also works fine with these methods on other SDKs (StarPRNT)

**Comment by mortenbekditlevsen** [comment]
In our POS system we've always been generating bitmaps of receipts for the graphics-only printers like the TSP1000 series. Also when using StarPRNT.

Please refer to similar discussions:

https://github.com/star-micronics/react-native-star-io10/issues/21

From one of the linked sources above:

"In particular, the TSP100 range does not have built-in font data, so is limited to printing graphically, and does not support the actionPrintText() method.
Instead, if you require support for the TSP100 range, you will need to build up your document as images and add them to the print job with the actionPrintImage() method."

This is from a discussion about another printer driver, but it's not about the driver, it's about the fact that the printer does not have font data and thus only supports a subset of the available driver commands across all platforms / sdks.

**Comment by yellowMonkeyMediaDev** [comment]
I'm facing the same issue, is there any solution for this?

**Comment by mortenbekditlevsen** [comment]
That's what we're doing at may job: we basically have a document format which can be rendered to various sources: html (for emailing), text (with hooks for various receipt printer integrations) and then UIViews which we then render to images and print on graphics-only printers.

**Comment by YuzoKato** [comment]
@mortenbekditlevsen 
Thank you for the explanation.

@davidhole @yellowMonkeyMediaDev 
 TSP100III series is a graphic-only printer. You need to use [actionPrintImage](https://star-m.jp/products/s_print/sdk/starxpand/manual/en/ios-swift-api-reference/star-xpand-command/printer-builder/action-print-image.html).  The provided project you can build uses [actionPrintText](https://star-m.jp/products/s_print/sdk/starxpand/manual/en/ios-swift-api-reference/star-xpand-command/printer-builder/action-print-text.html) only. So, TSP100III cannot print as you expected.  
You can refer to [Text-to-Graphic sample code](https://github.com/star-micronics/StarXpand-SDK-iOS/blob/main/example/StarXpandSDK/PrintingSamples/Sample15_GraphicReceipt.swift). This sample includes a converting function from text to graphic so that you can use text to create printing data.

TSP100IV model supports [actionPrintText](https://star-m.jp/products/s_print/sdk/starxpand/manual/en/ios-swift-api-reference/star-xpand-command/printer-builder/action-print-text.html).

**Comment by BryanJBryce** [comment]
I made an extension to `PrinterBuilder` for convenience:

`extension StarIO10.StarXpandCommand.PrinterBuilder {
    @objc public func actionPrintImageFromText(_ text: String, font: UIFont? = nil) -> Self {
        actionPrintImage(createImageParameterFromText(text, font: font))
    }

    func createImageParameterFromText(_ text: String, font: UIFont?) -> StarXpandCommand.Printer.ImageParameter {
        let width = maxWidth
        let font = font ?? UIFont.monospacedSystemFont(ofSize: 24, weight: .medium)
        let bitmap = createBitmapFromText(text, font: font, width: width)
        return StarXpandCommand.Printer.ImageParameter(image: bitmap, width: width)
    }

    func createBitmapFromText(_ text: String, font: UIFont, width: Int) -> UIImage {
        let attributeDic = NSDictionary(dictionary: [NSAttributedString.Key.font: font])
        let widthCGF = CGFloat(width)
        let stringDrawingOptions: NSStringDrawingOptions = [NSStringDrawingOptions.usesLineFragmentOrigin, NSStringDrawingOptions.truncatesLastVisibleLine]

        let size: CGSize = (text.boundingRect(with: CGSize(width: widthCGF, height: 10_000), options: stringDrawingOptions, attributes: attributeDic as? [NSAttributedString.Key: Any], context: nil)).size

        if UIScreen.main.responds(to: #selector(NSDecimalNumberBehaviors.scale)) {
            if UIScreen.main.scale == 2.0 {
                UIGraphicsBeginImageContextWithOptions(size, false, 1.0)
            } else {
                UIGraphicsBeginImageContext(size)
            }
        } else {
            UIGraphicsBeginImageContext(size)
        }

        let context: CGContext = UIGraphicsGetCurrentContext()!

        UIColor.white.set()

        let rect = CGRect(x: 0, y: 0, width: size.width + 1, height: size.height + 1)

        context.fill(rect)

        let attributes = NSDictionary(dictionary: [NSAttributedString.Key.foregroundColor: UIColor.black, NSAttributedString.Key.font: font])

        text.draw(in: rect, withAttributes: attributes as? [NSAttributedString.Key: Any])

        let imageToPrint: UIImage = UIGraphicsGetImageFromCurrentImageContext()!

        UIGraphicsEndImageContext()

        return imageToPrint
    }
}`

**Comment by Tatsuki-Yamamoto2731** [comment]
It seems that this issue was resolved, so I am closing this Issue.

**Comment by MarsYoung** [comment]
I have the same problem, but why can  the Star Quick Setup Utility print the text clean and tidy. 
Converting to image cause  ugly text words.

**Comment by Tatsuki-Yamamoto2731** [comment]
@MarsYoung 
[This sample](https://github.com/star-micronics/StarXpand-SDK-iOS/blob/main/example/StarXpandSDK/PrintingSamples/GraphicSamples/GraphicSample01_GraphicReceipt.swift) shows how to generate graphic data from text data. Does this sample show you a solution? 
If not, I would like to know the details of the problem. Please open a new Issue and describe the situation as accurately as possible.

**Comment by axelmarciano** [comment]
I ran into the same issue and found that relying on actionPrintImage as a workaround is far from ideal—both in terms of performance and print quality. So, I took matters into my own hands and forked [react-native-star-prnt](https://github.com/infoxicator/react-native-star-prnt) to update it.

I integrated the latest SDK from [star-micronics/starprnt-sdk-ios-swift](https://github.com/star-micronics/starprnt-sdk-ios-swift) to ensure compatibility with the most recent versions of iOS, Android, and React Native.

Now, printing works flawlessly on these printers across both platforms.

You can check out my updated package here: [rn-star-prnt](https://github.com/axelmarciano/rn-star-prnt).
