### ISSUE TITLE
Changelog for 2.4.0 has misleading support version change

### ISSUE THREAD

**Issue by nickdnk** [star-micronics/StarXpand-SDK-iOS#26]
Hello

You've stated in version 2.4.0 (https://github.com/star-micronics/StarXpand-SDK-iOS/releases/tag/2.4.0) that you now require iOS 13, however, you did not update your package.swift file to indicate this:

```swift
import PackageDescription

let package = Package(
    name: "StarIO10",
    platforms: [.iOS(.v12)], // <! Should be v13
    products: [
        .library(
            name: "StarIO10",
            targets: ["StarIO10"]),
    ],
    dependencies: [],
    targets: [
        .binaryTarget(
            name: "StarIO10",
            path: "StarIO10.xcframework")
    ]
)
```

This is hugely problematic, as automatic updates of the package will now install version >= 2.5.0 in projects targeting iOS 12. You **must** retroactively correct this mistake by republishing all versions from 2.5.0 and later with the correct package file.

Edit: Reading the rest of the changelog, it would indicate that iOS 12 is somehow still supported. Can you please explain what **Changed minimum supported OS version from 12 to 13** means, if it doesn't mean you don't support iOS 12? This is very confusing to be honest.

Edit again: After reading I've come to the conclusion that the SDK still works for iOS 12. I would recommend you change the release notes to not say you've raised the minimum supported OS version when this is in fact not the case.

**Comment by Tatsuki-Yamamoto2731** [comment]
@nickdnk STAR has tested the operation on iOS13 or higher, but not on iOS12.
STAR considers the version STAR can guarantee to work as the minimum supported OS version.

**Comment by nickdnk** [comment]
Okay, but I would then encourage you to update the wording in the changelog to clarify that. In the context of minimum iOS version, "required" is usually equivalent to "supported".

**Comment by Tatsuki-Yamamoto2731** [comment]
@nickdnk Thank you for your opinion, STAR will consider it.
