### ISSUE TITLE
Privacy Report reported as incorrect format 

### ISSUE THREAD

**Issue by robertsammons** [star-micronics/StarXpand-SDK-iOS#27]
`ITMS-91056: Invalid privacy manifest - The PrivacyInfo.xcprivacy file from the following path is invalid: “Frameworks/StarIO10.framework/PrivacyInfo.xcprivacy”. While no action is required at this time, starting May 1, 2024, when you upload a new app or app update, keys and values in your app’s privacy manifest must be in a valid format. For more details about privacy manifest files, visit: https://developer.apple.com/documentation/bundleresources/privacy_manifest_files.
`
App Store Connect is reporting that the privacy manifest is invalid when submitting a new build. On the latest 2.6.0 that includes this.

**Comment by Tatsuki-Yamamoto2731** [comment]
@robertsammons Thank you for your report.
We are currently investigating this issue. We will be releasing an update to address this issue.
We apologize for the inconvenience and appreciate your understanding.
We will keep you updated as we make progress.
