### ISSUE TITLE
Cocoapods support

### ISSUE THREAD

**Issue by davidhole** [star-micronics/StarXpand-SDK-iOS#3]
Hi there!

We are working on a flutter plugin for the StarXpand SDK (iOS and Android). Flutter plugins only support Cocoapods and not Swift PM.

Any chance that you can add support for Cocoapods to this SDK?

Thanks in advance!
Dave

**Comment by nneuberger1** [comment]
@davidhole I found this flutter project for Star printers.

https://pub.dev/packages/flutter_star_prnt
https://github.com/Eddayy/flutter_star_prnt

Although, so far, I haven't been successful yet at printing from their sample application. I have a wired Star Micronics mC-Print3 Thermal Printer Model MCP30.

I'm looking for the same thing. I have several flutter applications and also familiar with Swift so I might be able to help build a flutter wrapper.


Have you found any flutter solutions yet for Star printers?

**Comment by davidhole** [comment]
Hey @nneuberger1,

I did create a flutter package which is now running in production for our app.

It's not in pub.dev yet but will be soon...

Here is the source :)

https://github.com/ovatu/starxpand_flutter

**Comment by nneuberger1** [comment]
@davidhole awesome! It looks like a full port to Flutter. I noticed even an open drawer function. I'll fork it for now. Thanks for the contribution!

**Comment by davidhole** [comment]
@nneuberger1 No worries!

Yep, we got most functionality in there including drawers and barcode scanners.

Hope it works out for you and if you have any improvements, feel free to PR :)

**Comment by nneuberger1** [comment]
Some better flutter related discussions found here.  https://github.com/ovatu/starxpand_flutter/issues/1

**Comment by Tatsuki-Yamamoto2731** [comment]
@davidhole @nneuberger1 
Unfortunately, we have no plan to support CocoaPods in StarXpand SDK so far. Sorry for any inconvenience.
We appreciate your ingenious use of our library.
I am closing this Issue, but we received your feedback.
