### ISSUE TITLE
Port open failure may occur on LAN I/F with continuous open/close

### ISSUE THREAD

**Issue by KHosozawa** [star-micronics/StarXpand-SDK-iOS#32]
# Phenomenon
When repeatedly printing with an execution of [`StarPrinter.open()`](https://star-m.jp/products/s_print/sdk/starxpand/manual/en/ios-swift-api-reference/star-printer/open-async.html#ios-swift-star-printer-open-async) and [`StarPrinter.close()`](https://star-m.jp/products/s_print/sdk/starxpand/manual/en/ios-swift-api-reference/star-printer/close-async.html#ios-swift-star-printer-close-async) methods via LAN interface, [`StarIO10Error.inUse`](https://star-m.jp/products/s_print/sdk/starxpand/manual/en/ios-swift-api-reference/star-io10-error/index.html#ios-swift-star-io10-in-use-error) error may be occurred in `StarPrinter.open()` method.

# Conditions for Occurrence
* Printer Interface: LAN (both wired and wireless)
* When the Auto Switch Interface feature of StarIO10 is turned off, or when the connected printer model does not support the Auto Switch Interface. 
    - Auto Switch Interface feature: https://star-m.jp/products/s_print/sdk/starxpand/manual/en/ios-swift-api-reference/star-connection-settings/auto-switch-interface.html
* After executing the `StarPrinter.close()` method on the printer, if the `StarPrinter.open()` method is executed on the same printer within a few hundred milliseconds.

# Cause
It has been identified that after calling the iOS API by Apple Inc. to close the communication port of the printer, there can be a delay before the iOS device sends the communication for the closing process. 
During this interval, until the printer receives the port closing process from the iOS device, the next port opening will fail.

# Workaround
If the `StarIO10Error.inUse` error is thrown, please add an `wait` for approximately 500 milliseconds (*) before re-executing the `StarPrinter.open()` method.
* In our testing, we have confirmed that a wait time of 500 milliseconds prevents this issue from occurring. However, please adjust according to your individual environment.

**Comment by wangchun0129** [comment]
用的最新版本,2.8.0,打开 打印机时依然显示Error: inUse(message: "The device is in use by another host.", errorCode: none)，这是什么原因呢？

**Comment by KHosozawa** [comment]
@wangchun0129 

Thank you for the information.
Our tests have not confirmed this problem with version 2.8.0.
We would like to hear more details in order to investigate the cause.

Is your post the same story as #35? If so, please let me continue the story in #35.

Best regards.
