### ISSUE TITLE
Getting Write failed when application is backgrounded  for a minute and back to foregound on iOS

### ISSUE THREAD

**Issue by mehtahardikr** [star-micronics/StarXpand-SDK-iOS#33]
## Description
start monitor printer ( Lan Interface ) , put app in background, open another apps and back to app around after 60 secs.
and try to check printer status.

## Your device where the bug occurs 
 - Device: 
    *iPad (5th generation)*
 - OS:
    *iOS 16.5*

## Your printer
- Model Names:
    *mC-Print3*
- Firmware Version:
    *e.g. 3.81*
- Interface:
    *Ethernet*

## To Reproduce
1. start monitor printer ( Lan Interface )
2. put app in background
3. open another apps and back to app around after 60 secs
4. check printer status.

## Expected behavior
it keep throwing following logs in background.
```
[connection] nw_write_request_report [C1] Send failed with error "Socket is not connected"
[connection] nw_flow_add_write_request [C1 192.168.29.86:9100 failed channel-flow (satisfied (Path is satisfied), interface: en0[802.11], ipv4, ipv6, dns)] cannot accept write requests
[connection] nw_write_request_report [C1] Send failed with error "Socket is not connected"
```
It should not and while checking  printer status, it should not throw  "Not opened"  error

**Comment by KHosozawa** [comment]
@mehtahardikr  Thank you for your report.
We have tested the operation under close conditions and could not reproduce this issue.
Could you please provide us with the following information so that we can investigate further?

- Xcode version
- Is this problem occurring in the application you are creating? Does it occur in the sample code of this project?
- Does this issue occur on other iOS devices?

**Comment by mehtahardikr** [comment]
You have to keep monitor printer and switch to another applications and
around 60 secs you have to go back to the app you will see that logs like
write failed adn then after not able to print as it keep says not opened.
Its on Ipad and yes happening on other iPads too. Its just demo app to
integrate star printer and check its functionalities.

**Comment by KHosozawa** [comment]
@mehtahardikr 
Thank you for your response.
We will check the operation and let you know if we make any progress.
Can you tell us what version of Xcode you are using?

**Comment by KHosozawa** [comment]
@mehtahardikr 
Thanks for the information.

We have confirmed that this problem occurs when the app does not execute `stopMonitoring()` when it transitions to the background.
If this is the case for your app, please execute `stopMonitoring()` when transitioning to the background.

In this project, [MonitorViewController.swift](https://github.com/star-micronics/StarXpand-SDK-iOS/blob/main/example/StarXpandSDK/MonitorViewController.swift), `stopMonitoring()` is executed in `viewWillDisappear()` and `willResignActive()`.

Best regards.
