### ISSUE TITLE
How can I use this SDK to print image with grayscale? All images I printed are monochrome on receipt.

### ISSUE THREAD

**Issue by Sred1992** [star-micronics/StarXpand-SDK-iOS#36]
## Description
Same as the title.

**Comment by KHosozawa** [comment]
@Sred1992 
Sorry, our printers only support monochrome printing and not grayscale printing.
However, you can use `setEffectDiffusion(_:)` and `setThreshold(_:)` in the `ImageParameter` class to adjust the printed image. If you have not tried it yet, please try that.

https://star-m.jp/products/s_print/sdk/starxpand/manual/en/ios-swift-api-reference/star-xpand-command/printer/image-parameter/index.html#ios-swift-star-xpand-command-printer-image-parameter

Best regards.

**Comment by Sred1992** [comment]
Still not what I want, but thanks anyway!
