### ISSUE TITLE
Exact Version Number for SPM

### ISSUE THREAD

**Issue by robertsammons** [star-micronics/StarXpand-SDK-iOS#4]
Set exact version on swift package manager to 2.2.0.

Xcode fails to find the dependency from GitHub `Dependencies could not be resolved because no versions of 'starxpand-sdk-ios' match the requirement 2.2.0 and root depends on 'starxpand-sdk-ios' 2.2.0.`

Setting to main branch works

**Comment by bandit-ibayashi** [comment]
@robertsammons I have changed the tag name "V2.2.0" to "2.2.0", then this issue was solved in my environment.
Could you please check again?

Thank you for your report!

**Comment by robertsammons** [comment]
@bandit-ibayashi thank you all sorted 🙂
