### ISSUE TITLE
Open Drawer with StarXpand

### ISSUE THREAD

**Issue by thomazDeveloper** [star-micronics/StarXpand-SDK-iOS#5]
I have a TSP100III printer with a drawer and would like to open the drawer after printing the receipt. May I have an example by using StarXpand

## Your device where the bug occurs 
 - Device: 
   Ipad
 - OS:
  iOS 15.0 

## Your printer
- Model Names:
   TSP100III
- Firmware Version:
   not sure
- Interface:
    usb

**Comment by nneuberger1** [comment]
@bandit-ibayashi solution to open the cash drawer worked fine. I verified connected to a wired Star Micronics mC-Print3 Model MCP30. I was using Xcode 13.4 with iPhone Pro Max 13 Simulator and using the sample code from the sample application provided by this project.
