### ISSUE TITLE
[Crash] EXC_BAD_ACCESS

### ISSUE THREAD

**Issue by WenzhaoTan-Chowbus** [star-micronics/StarXpand-SDK-iOS#7]
## Description
Catching a crash via Firebase.

## Your device where the bug occurs 
 - Device: 
    iPad (9th generation)
 - OS:
    15.5.0
 - Version
    2.2.0

## Your printer
- Model Names:
    mC-Print3
- Firmware Version:
    3.4
- Interface:
    Ethernet

## Your development environment
ProductName: macOS
ProductVersion: 12.6
BuildVersion: 21G115

## Additional context
```
Crashed: StarIO10.StarPrinter
0  libswiftCore.dylib             0x3da9a0 swift_getObjectType + 56
1  StarIO10                       0x74e58 __swift_allocate_value_buffer + 4788
2  StarIO10                       0x353e0 block_destroy_helper.44 + 17476
3  StarIO10                       0x3273c block_destroy_helper.44 + 6048
4  StarIO10                       0x662a4 __swift_memcpy1_1 + 668
5  libdispatch.dylib              0x1e6c _dispatch_call_block_and_release + 32
6  libdispatch.dylib              0x3a30 _dispatch_client_callout + 20
7  libdispatch.dylib              0xb124 _dispatch_lane_serial_drain + 668
8  libdispatch.dylib              0xbc80 _dispatch_lane_invoke + 392
9  libdispatch.dylib              0x16500 _dispatch_workloop_worker_thread + 648
10 libsystem_pthread.dylib        0x10bc _pthread_wqthread + 288
11 libsystem_pthread.dylib        0xe5c start_wqthread + 8
```

**Comment by bandit-ibayashi** [comment]
@WenzhaoTan-Chowbus Thank you for your patience.

Unfortunately we have not been able to reproduce this error. 
Could you please tell us in the following information?
* What your development environment
   + Now that we know the PC version, it would be helpful to have the Xcode version by running `xcodebuild -version`
* Which steps to take to get this error
* What the expected behavior is

**Comment by Tatsuki-Yamamoto2731** [comment]
I am closing this Issue. If you still have this issue, please reopen it.
